### ISSUE TITLE
Huge Memory Leak

### ISSUE THREAD

**Issue by PadreWoW** [talamortis/OregonCore#246] opened 2021-04-07 07:15 UTC
**Describe the bug**
Huge Memory Leak
1,5Gb Ram every 8 hours (4-7 players)

**To Reproduce**
Just start the core and add 4-7 players
After 1 day there will be about 4Gb Ram consumed

**Branch**
master

**Eluna**
- [V] Enabled
- [ ] Disabled

**HASH/COMMIT:**
https://github.com/talamortis/OregonCore/commit/cb0b1e3b0eaa0c079a6ef77a348127284a1703fe

**Comment by PadreWoW** [comment] 2021-04-08 10:58
Problem in GridUnload = 0
I'm shure 100%

With GridUnload = 1 there are leak about 40-50MB RAM per hour
and with GridUnload = 0 leak about 300-500MB RAM per hour

**Comment by milestorme** [comment] 2021-04-08 11:12
Grid unload 0 allows all maps to stay loaded so you will see memory rise to an extent , as it is not unloading any maps , it should level out once all maps are loaded  , I was unable to keep the server up long enough to test due to random crashes with 6-8 player .

**Comment by talamortis** [comment] 2021-05-02 22:35
Looks like the issue is todo with stairs of destiny event

**Comment by talamortis** [comment] 2021-05-03 09:21
hopefully fixed in https://github.com/talamortis/OregonCore/commit/ad9bf61eb45a4905de88e69b3558e82b19d124fa

Will close issue please comment if still happens then will re-open

**Closed as completed** 2021-05-03 09:24 UTC
