### ISSUE TITLE
Memory leak [Update time diff]

### ISSUE THREAD

**Issue by diluh** [talamortis/OregonCore#112] opened 2019-12-23 19:09 UTC
**Operating system:** Ubuntu 18

**Current behavior :** Core does not support getting 1 day online as [Update time diff] is increasing a lot and leaving all players with Lag and Delay

![image](https://user-images.githubusercontent.com/46387591/71375647-c1383180-259d-11ea-90f8-707ed55dd772.png)
![image](https://user-images.githubusercontent.com/46387591/71375665-d1e8a780-259d-11ea-8170-cfff96c25f41.png)

**AC HASH/COMMIT:** **Branch: Eluna:**
https://github.com/talamortis/OregonCore/commit/132190d6d57be00ef27117da6db28d3108091430

**Comment by PadreWoW** [comment] 2019-12-24 10:48
2.5 hours online and Update time diff: 16 - all fine.....

**Comment by diluh** [comment] 2019-12-24 11:07
It is a good test with active players playing. Every day I have this delay

picture now
![image](https://user-images.githubusercontent.com/46387591/71410514-6269cb00-2624-11ea-98f8-82966394bf59.png)

**Comment by PadreWoW** [comment] 2019-12-24 11:09
I'm alone on my test server and my test server is VERY weak (i5 2310, 16GB Ram, old HDD)

2.48 hours uptime

**Comment by diluh** [comment] 2019-12-24 11:10
Anyways could you send me your [oregoncore.conf] file so that I can compare with mine?

**Comment by PadreWoW** [comment] 2019-12-24 11:11
later - after 1 day uptime

**Comment by PadreWoW** [comment] 2019-12-24 12:17
4 hours uptime - all fine - Update time diff: 15-16

**Comment by PadreWoW** [comment] 2019-12-24 13:45
5.30 hours uptime - all fine - Update time diff: 15-16

**Comment by talamortis** [comment] 2019-12-24 21:43
if you have 0 players online i doubt your server uptime will increase, Maybe its something todo with Grid or maybe maps or even could be something with creatureAI.

**Comment by coolzoom** [comment] 2019-12-25 07:39
i realize the update diff issue for the old core, some people has added an auto-shutdown each day, does it getting worse after restructure?

**Comment by PadreWoW** [comment] 2019-12-25 07:41
I have no such problem on old core....
Uptime more than 7 days and 4-7 players

**Comment by coolzoom** [comment] 2019-12-25 14:34
i was played on a oregoncore server back to 2016 and it has 100+ players and the server has auto-restart each day(due to the spell lag at evening).
never played on a server more than that after 2017.
i might be wrong, probably the issue has long gone.

**Comment by PadreWoW** [comment] 2019-12-25 14:35
My old server has rev 3559+ - no problem with Update time diff

**Comment by coolzoom** [comment] 2019-12-25 14:37
so might be also server performance issue? like if you has a low performace server with less horse power, it may have higher update diff in the long run.

**Comment by PadreWoW** [comment] 2019-12-25 14:39
My old server has these parameters:
Intel I7 4770T
16Gb RAM (2x8)
Seagate HDD ST1000VX005

Not so strong.....

my test server is VERY weak (i5 2310, 16GB Ram, old HDD)
and no problem with last core

**Comment by coolzoom** [comment] 2019-12-25 14:42
looks like strong enough, probably such configureation can handle over 500 players if the internet bandwidth is enough😄

**Comment by coolzoom** [comment] 2019-12-25 14:44
@diluh what is your configuration do you mind to let us know?

**Comment by diluh** [comment] 2019-12-27 10:15
@coolzoom 
Ubuntu 18.04 LS
2vCPU 7.5GB RAM
100 SSD

**Comment by talamortis** [comment] 2019-12-27 23:20
Ok, So after further looking into the issue, it looks like the problem is down to grid loading or maybe SmartAI, Upon player entering an instance the Update diff increases, Best instance to test at is Karazhan.

Enter the instance do .server info, walk near the stairs (towards moroes) and do .server info agan.

**Comment by coolzoom** [comment] 2020-01-01 14:05
first try without cast spell and kill mobs
1, .go -11113 -2006 49.33 0 , diff 16
2, .go -11095 -1989 51 532 , diff 16
3, .go creature 81435, diff 16
CPU: I7 4770K
OS: WIN10x64 
RAM 16GB, 
SSD
![image](https://user-images.githubusercontent.com/10232727/71642212-dcfcaf80-2ce2-11ea-9b98-0f0e07a634c7.png)

second try with GM mode off, and mob is casting AI, work from entrance to the stairs near moroes
![image](https://user-images.githubusercontent.com/10232727/71642270-aa9f8200-2ce3-11ea-96ea-95be46ac59cb.png)

1hour
![image](https://user-images.githubusercontent.com/10232727/71642638-4f708e00-2ce9-11ea-9043-df8b7af03218.png)

**Comment by talamortis** [comment] 2020-01-01 20:51
Are you compiling in debug or release?

Edit: Ok it looks like this issue is caused in debug mode. this is some of the code is not being optimized out. Please Compile in release and then test.

**Comment by coolzoom** [comment] 2020-01-02 01:50
> Are you compiling in debug or release?
> 
> Edit: Ok it looks like this issue is caused in debug mode. this is some of the code is not being optimized out. Please Compile in release and then test.

I was trying to find where was the issue so im was using Relwithdebinfo and run directly under visual studio debug mode, but it looks normal so i just cut the screenshot.
![image](https://user-images.githubusercontent.com/10232727/71648903-19f98e00-2d45-11ea-8bf6-92e1cd446003.png)

more details:
mysql5.5.62
openssl 1.0.2o
ace6.5
visual studio 2017

**Comment by talamortis** [comment] 2020-01-02 06:45
Will close this issue.

**Closed as completed** 2020-01-02 06:45 UTC
Labels: invalid, wontfix
